conversion:
    description: >
        Gather the most crucial information about the event: {event}.
        You should gather the following if there if:
            1. Date in format DD/MM/YYYY
            2. Start time in format HH:MM
            3. End time in format HH:MM
            4. Event title, generate if not explicit
        Make sure you are sending a valid date.
    expected_output: >
        A comprehensive list of all the key details of the event.

manage_timetable:
    description: >
        Manage a timetable at your disposition. You can access it through the tools. Only you can access it.
        You will have to handle this new event: {event}.
        If you are removing a slot, make sure to access the timetable first to make sure which slot is {event} talking about. It might not be
        the same title.
    expected_output: >
        A short answer summarizing what slot was added or deleted and when.